version: '3'
services:
  app:
    build: .
    container_name: AppOrders
    volumes:
      - .:/app
    command: python main.py
  test:
    build: .
    container_name: TestOrders
    volumes:
      - .:/app
    command: python -m unittest test_main.py
