import pandas as pd

dataFrame = pd.read_csv('orders.csv')
    
dataFrame['order_date'] = pd.to_datetime(dataFrame['order_date'])

dataFrame['month'] = dataFrame['order_date'].dt.to_period('M')
monthlyRevenue = dataFrame.groupby('month').apply(lambda x: (x['product_price'] * x['quantity']).sum())
print("Total revenue generated by the online store for each month:")
print(monthlyRevenue)

monthlyRevenue = dataFrame.groupby('product_name').apply(lambda x: (x['product_price'] * x['quantity']).sum())
print("\nTotal revenue generated by each product:")
print(monthlyRevenue)

monthlyRevenue = dataFrame.groupby('customer_id').apply(lambda x: (x['product_price'] * x['quantity']).sum())
print("\nTotal revenue generated by each customer:")
print(monthlyRevenue)

top_10_Customers = monthlyRevenue.nlargest(10)
print("\nTop 10 customers by revenue generated:")
print(top_10_Customers)
